### ISSUE TITLE
Permanent use

### ISSUE THREAD

**Issue by j1nzin** [valignatev/socd#40] opened 2024-08-10 21:01 UTC
Hi, Excuse my ignorance, but is there a way to activate it and make it permanent without keeping the window open?
that the window is closed and kept forever.

sorry for the inconvenience, ty

**Comment by Lee-The-Tree** [comment] 2024-08-11 00:40
there is no minimize rn he is rewriting the whole thing so i would say just wait for that it still works really well rn

**Comment by valignatev** [comment] 2024-09-18 15:01
Duplicate of #39

**Closed by valignatev** 2024-09-18 15:01 UTC
